Traceback (most recent call last):
  File "/mnt/xiaodi/cocogum_refactor/datapreprocess/CodeSearchNet/get_git_respository.py", line 48, in download_repository
    urllib.request.urlretrieve(url, save_path)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/mnt/xiaodi/cocogum_refactor/datapreprocess/CodeSearchNet/get_git_respository.py", line 48, in download_repository
    urllib.request.urlretrieve(url, save_path)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/mnt/xiaodi/cocogum_refactor/datapreprocess/CodeSearchNet/get_git_respository.py", line 48, in download_repository
    urllib.request.urlretrieve(url, save_path)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/yanlwang/anaconda3/envs/tf2/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
